/**
 * Copyright (C) 2010-18 diirt developers. See COPYRIGHT.TXT
 * All rights reserved. Use is subject to license terms. See LICENSE.TXT
 */
package org.diirt.graphene;

import java.awt.Graphics2D;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import org.diirt.util.array.ArrayDouble;

/**
 *
 * @author carcassi
 */
public class ShowResizableImage extends javax.swing.JFrame {

    /**
     * Creates new form ShowImage
     */
    public ShowResizableImage() {
        initComponents();
        imagePanel.setImage(new BufferedImage(renderer.getImageWidth(), renderer.getImageHeight(), BufferedImage.TYPE_3BYTE_BGR));
        addComponentListener(new ComponentAdapter() {

            @Override
            public void componentResized(ComponentEvent e) {
                renderer.update(new AreaGraph2DRendererUpdate()
                        .imageHeight(getRootPane().getHeight())
                        .imageWidth(getRootPane().getWidth()));
                imagePanel.setImage(new BufferedImage(renderer.getImageWidth(), renderer.getImageHeight(), BufferedImage.TYPE_3BYTE_BGR));
                redrawHistogram();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new org.diirt.graphene.ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel.setLayout(new java.awt.FlowLayout());
        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Cell1DDataset hist;
    private AreaGraph2DRenderer renderer = new AreaGraph2DRenderer(300, 200);

    public void setHistogram(Cell1DDataset hist) {
        this.hist = hist;
        pack();
        redrawHistogram();
    }

    private int count = 0;
    private long totalTime;

    private void redrawHistogram() {
        count++;
        long startTime = System.nanoTime();
        BufferedImage image = (BufferedImage) imagePanel.getImage();
        Graphics2D graphics = (Graphics2D) image.getGraphics();
        renderer.draw(graphics, hist);
        imagePanel.setImage(image);
        long endTime = System.nanoTime();
        totalTime += endTime - startTime;
        if (count % 100 == 0)
            System.out.println(count + " " + (totalTime / count));
    }



    public static void showHistogram(final Cell1DDataset hist) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ShowResizableImage frame = new ShowResizableImage();
                frame.setHistogram(hist);
                frame.setVisible(true);
            }
        });

    }

    public static void main(String args[]) throws Exception {
        Cell1DDataset hist = Cell1DDatasets.linearRange(new ArrayDouble(30, 14, 150, 160, 180, 230, 220, 350, 400, 450, 500,
                                        350, 230, 180, 220, 170, 130, 80, 30, 40), 0.0, 2.0);
        showHistogram(hist);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.diirt.graphene.ImagePanel imagePanel;
    // End of variables declaration//GEN-END:variables
}
